config/routes.rb
JuliesolimanFinalproject::Application.routes.draw do
  root "posts#home"
  resources :users, :except => [:edit, :update]
  resources :sessions, :only => [:create, :destroy, :new]
  resources :posts, :except => [:show]
  resources :follows, :only => [:new, :destroy, :show]
  resources :likes, :only => [:new, :destroy]
  resources :comments, :only => [:create]
  resources :topics, :only => [:show]

  get "/logout" => "sessions#destroy", as: 'logout'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :followers, :class_name => 'Follow', :foreign_key => 'leader_id', :dependent => :destroy
  has_many :leaders, :class_name => 'Follow', :foreign_key => 'follower_id', :dependent => :destroy

  # all fields are mandatory, email must be unique, password a certain length
  validates :email, uniqueness: {case_sensitive: false}
  validates_presence_of :email, :name, :password
  validates :password, length: {in: 6..20}

  before_save do
    self.email = self.email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def redirect_to_current_url(notice_string)
      session[:return_to] ||= request.referer
      if notice_string
        redirect_to session.delete(:return_to), notice: notice_string
      else
        redirect_to session.delete(:return_to)
      end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).order("updated_at desc")
    if session[:user_id] != @user.id
      @can_edit = false
    else
      @can_edit = true
    end

    f = Follow.find_by(leader_id: params[:id], follower_id: session[:user_id])
    if f.nil?
      @can_follow = true
    else
      @can_follow = false
    end
  end

  def create
    @user = User.new
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.password_confirmation = params[:password_confirmation]

    @user.save
    if @user.errors.any?
      @user.errors.full_messages.each do |msg|
        redirect_to_current_url msg
      end
    else
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver
      redirect_to root_url, notice: "Thanks for signing up, #{@user.name}!"
    end
  end

  def index
    @users = User.all.order("created_at desc")
  end

  def destroy
    user = User.find_by(params[:id])
    user.destroy
    redirect_to logout_url
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% @users.each do |user| %>
  <div class="row">
        <h2><%= link_to user.name, user_path(user.id) %></h2>
        <p>Email: <%= user.email %></p>
        <p>Joined on: <%= user.created_at %></p>
        <h4><%= link_to "Following: #{user.leaders.count} | Followers: #{user.followers.count}", follow_path(user.id) %></h4>
  </div>
<%end%>

app/views/users/index.html.erb
<h1 class="page-header">All Users</h1>
<%= render "user" %>

app/views/users/new.html.erb
<h1>Sign Up!</h1>

<%= form_tag "/users" do %>

  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <br>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <br>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= label_tag :password_confirmation %>
  <%= password_field_tag :password_confirmation %>
  <br>
  <%= submit_tag "Sign Up!" %>

<% end %>

app/views/users/show.html.erb
<h1 class="page-header">Profile</h1>
 <% if @can_edit %>
  <%= link_to "Delete Account", user_path(@user.id), :method => 'delete',
              :class => "pull-right btn btn-success btn-large btn-danger" %>
  <% end %>

  <% @users = [@user] %>
  <%= render "user" %>

 <% if @can_edit %>
  <div class="row">
    <div class="col-md-6">
      <%= form_tag posts_url, :method => 'post' do %>
        <div class="form-group">
          <%= label_tag :post_text %>
          <%= text_field_tag :post_text, "", class: 'form-control', placeholder: 'Enter text here' %>
        </div>

        <div class="form-group">
          <%= label_tag :topic_id, "Topic" %>
          <%= select_tag :topic_id, options_from_collection_for_select(Topic.all.order('name asc'), :id, :name), class: 'form-control', multiple: true, prompt: "Select optional topics" %>
        </div>

        <%= submit_tag 'Post', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
<% else %>
   <% if @can_follow %>
    <%= link_to "Follow", new_follow_path(@user.id),
              :class => "pull-right btn btn-success btn-large" %>
    <% else %>
     <%= link_to "Unfollow", follow_path(@user.id), :method => 'delete',
              :class => "pull-right btn btn-success btn-large btn-danger" %>
  <% end %>

 <% end %>

<%= render "posts/posts" %>