config/routes.rb
JuliesolimanFinalproject::Application.routes.draw do
  root "posts#home"
  resources :users, :except => [:edit, :update]
  resources :sessions, :only => [:create, :destroy, :new]
  resources :posts, :except => [:show]
  resources :follows, :only => [:new, :destroy, :show]
  resources :likes, :only => [:new, :destroy]
  resources :comments, :only => [:create]
  resources :topics, :only => [:show]

  get "/logout" => "sessions#destroy", as: 'logout'

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :likers
  has_many :commenters
  has_many :mentions
  has_many :topics, through: :mentions, dependent: :destroy

  validate :post_text_entered

  def post_text_entered
    if text.blank?
      errors.add(:text, "cannot be empty")
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login, :except => [:home, :login]
  before_action :identify_user

  def identify_user
    user = User.find_by(id: session[:user_id])
    if user
      @username = user.name
    end
  end

  def require_login
    if session[:user_id].blank?
      redirect_to root_url, notice: "Nice Try!"
    end
  end

  def logout
    reset_session
    redirect_to root_url
  end

  def login
    session[:user_id] = params[:name]
    redirect_to root_url
  end

  def index
    @posts = Post.all.order("updated_at desc")
  end

  def destroy
    post_id = params["id"]
    p = Post.find_by(:id => post_id)
    u_id = p.user_id
    p.destroy
    redirect_to user_url(u_id)
  end

  def edit
    post_id = params["id"]
    @post = Post.find_by(:id => post_id)
  end

   def update
    post_id = params["id"]
    p = Post.find_by(:id => post_id)
    p.text = params["post_text"]
    p.save
    u_id = p.user_id
    redirect_to user_url(u_id), notice: "Post updated successfully!"
  end

  def create
      p = Post.new
      p.text = params["post_text"]
      p.user_id = session[:user_id]
      p.save

      if p.errors.any?
        p.errors.full_messages.each do |msg|
          redirect_to user_url(session[:user_id]), :notice => msg
        end
      else
        topic_ids = params["topic_id"]
        if topic_ids
            topic_ids.each do |topic_id|
              if !topic_id.blank?
                Mention.create(:topic_id => topic_id, :post_id => p.id)
              end
          end
        end
        redirect_to user_url(session[:user_id]), notice: "Posted!"
      end
  end

  def home
    if session[:user_id].blank?
      @logged_in = false
    else
      @logged_in = true
      follower_id = session[:user_id]
      leader_ids = User.joins(:followers).where("follower_id = #{follower_id}").uniq
      @posts = Post.where(user_id: leader_ids).order("updated_at desc")
    end
    @num_users = User.count
    @num_posts = Post.count
    @latest_post_time = Post.order("updated_at asc").first.updated_at
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <div class="row">
      <%user = post.user %>
      <h2><%= link_to user.name, user_path(user.id) %></h2>
      <p><%= post.text %></p>

      <div class="row">
         <% if @can_edit %>
          <%= link_to "Edit This Post", edit_post_path(post.id) %> |
          <%= link_to "Delete This Post", post_path(post.id), :method => 'delete' %>
         <%end%>
     </div>

     <% topics = post.topics %>
      <% if !topics.blank? %>
        <p>Topic(s):
        <% topics.each do |topic| %>
           <%= link_to topic.name, topic_path(topic.id) %>
        <% end %>
        </p>
      <% end %>

      <p>Likes: <%= Like.where(post_id: post.id).count %></p>
      <% if Like.find_by(post_id: post.id, user_id: session[:user_id] ) %>
        <%= link_to "Unlike", like_path(post.id), :method => 'delete',
              :class => "btn btn-success btn-large btn-danger" %>
      <% else %>
        <%= link_to "Like", new_like_path(post.id),
              :class => "btn btn-success btn-large" %>
      <% end %>

      <p>Comments: <%= Comment.where(post_id: post.id).count %></p>
      <% comments = Comment.where(post_id: post.id).order("updated_at asc") %>
      <% if !comments.nil? %>
        <% comments.each do |comment| %>
            <p>Comment by <%= link_to User.find_by(id: comment.user_id).name, user_path(comment.user_id) %> saying "<%= comment.text %>"</p>
        <% end %>
      <% end %>

      <div class="row">
        <div class="col-md-6">
          <%= form_tag comments_url(post.id), :method => 'post' do %>
            <div class="form-group">
              <%= label_tag :comment_text %>
              <%= text_field_tag :comment_text, "", class: 'form-control', placeholder: 'Enter comment here' %>
            </div>
            <%= submit_tag 'Comment', class: 'btn btn-default' %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  <h1>Edit Post</h1>
</div>

<div class="row">
  <div class="col-md-6">

    <%= form_tag "/posts/#{@post.id}", :method => 'patch' do %>

      <div class="form-group">
        <%= label_tag :post_text %>
        <%= text_field_tag :post_text, @post.text, class: 'form-control', placeholder: 'Edit text' %>
      </div>
      <%= submit_tag 'Update Post', class: 'btn btn-default' %>
    <% end %>

  </div>
</div>

app/views/posts/home.html.erb
<div>
  <h2>Flitter Stats</h2>
  <p> Number of users: <%=@num_users%></p>
  <p> Number of posts: <%=@num_posts%></p>
  <p> Last post at: <%=@latest_post_time%></p>
</div>


<% if @logged_in %>
  <h1 class="page-header">Feed</h1>
  <%= render "posts" %>
<% else %>
  <h2> Welcome to Flitter! You are not currently signed in. </h2>
  <p> New User? <%= link_to "Click here to sign up", new_user_url %> </p>
  <p> Returning User? <%= link_to "Click here to sign in", new_session_url %></p>
<% end %>

app/views/posts/index.html.erb
<h1 class="page-header">All Posts</h1>
<%= render "posts" %>